[package]
name = "spl-token-substream"
version = "0.1.0"
edition = "2021"

[lib]
name = "spl_token_substream"
crate-type = ["lib", "cdylib"]

[dependencies]
substreams = "^0.5.0"
substreams-solana = { git = "https://github.com/streamingfast/substreams-solana", branch = "master" }
prost = "0.11"
bs58 = "0.5.0"
substreams-solana-program-instructions = "0.1.1"
substreams-solana-structured-instructions = { git = "https://github.com/0xpapercut/substreams-solana-structured-instructions", branch = "main" }
substreams-solana-spl-token = { git = "https://github.com/0xpapercut/substreams-solana-spl-token", branch = "main" }
substreams-solana-utils = { git = "https://github.com/0xpapercut/substreams-solana-utils", branch = "main" }

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
[patch.'https://github.com/0xpapercut/substreams-solana-utils']
substreams-solana-utils = { git = "https://github.com/nabeel99/substreams-solana-utils", branch = "main" }
